### ISSUE TITLE
can't determine results is valid

### ISSUE THREAD

**Issue by houhaol** [RexBarker/VideoObjectRemoval#1]
Many thanks for this visualized derived work. I reproduced your steps but i met a assertation error, saying `AssertionError: Could not determine if results were valid!`

I guess it is permission error. My inpainting doesn't run. I have to add sudo before execution command.

**Comment by RexBarker** [comment]
Hi,
The `Could not determine if results were valid!` assertion occurs in `app/model.py` line 143.  This is a simple scan script that looks for the words "propagation has been finished" to occur in the model output.  This indicates that the inpaint model has completed all steps without error (3-basic steps: forward propagation, backward propagation, merge).

To debug this, I would first try to run the inpaint model alone with the example scripts ("flamingo" input masks & frames).  Here you would open a bash shell into the **inpaint** container, and execute the script `inpaint/scripts/test_inpaint_in_container.sh`, or from your host server bash prompt as `inpaint/scripts/test_inpaint_ex_container.sh`. This will give you the most basic test model.  Once this is working, you could test with the remote version of it from the **detect** container.  

If this is working, make sure that the communication between the containers is working.  Steps:
- open bash shell into **detect** container
- execute ssh from detect --> inpaint container:  `ssh appuser@inpaint` (password=appuser)
- if this works, then the SSH connection is ok.  
- you can also test this from within the **detect** container using the `detect/scripts/test_sshparamiko.py` script

If these work, but you still have problems, there could be an issue with the video size.  In practicality, this is limited by the inpaint model which accepts a maximum video resolution around 512 x 832.  Above this, the model will be truncated to that size.  The length also matters. You may max-out your GPU card at some point.  I was able to effectively run the model with an 8-GB GPU, but had my 11-GB card ready just incase.  I'm not sure this would be a limiting factor in your case.

**Comment by houhaol** [comment]
Thanks for your **QUICK** rely. The inpainting doesn't work as you suggest. I tried the test painting shell script. A error `RuntimeError: CUDNN_STATUS_EXECUTION_FAILED` pops out. 

But i thought my torch and cuda version should be fine?
> import torch
>print(torch.__version__)
0.4.0
> print(torch.version.cuda)
8.0.61

Anyway, i think it is my GPU card error. It says it requires CUDA_VERSION >= 9000 for
     optimal performance and fast startup time, but your PyTorch was compiled
     with CUDA_VERSION 8000. Please install the correct PyTorch binary.

Then seems i have to edit the Dockerfile and reinstall..

**Comment by RexBarker** [comment]
The docker file for the **inpaint** container should be ok. On line 1 of the _inpaint/docker/Dockerfile_: 
    `FROM nvidia/cuda:8.0-cudnn7-devel-ubuntu16.04`. 

As long as it's run from within this container, it should work.  You might want to check that the dependent functions compiled correctly with the _nvcc_ (run this from within the **inpaint** container).  
`/home/appuser/Deep-Flow/install_scripts.sh`
Sometimes the docker file does not build this correctly.  Also, this should be done after the `docker start inpaint` container operation, since a fresh container is sourced from the image, which might not have the correct compilation of the functions.

**Comment by houhaol** [comment]
Yeah. It is quite weird. My container and dependent functions should be fine. 

> Step 13/15 : RUN git clone https://github.com/RexBarker/Deep-Flow.git Deep-Flow
>  ---> Running in 9f61168d4443
> Cloning into 'Deep-Flow'...
> Removing intermediate container 9f61168d4443
>  ---> 24dee0113644
> Step 14/15 : WORKDIR /home/appuser/Deep-Flow
>  ---> Running in bcd108036555
> Removing intermediate container bcd108036555
>  ---> 622ee5b239a1
> Step 15/15 : RUN chmod +x /home/appuser/Deep-Flow/install_scripts.sh &&     bash ./install_scripts.sh
>  ---> Running in 3e5fdad78546
> Compiling resample2d kernels by nvcc...
> rm: cannot remove 'Resample2d_kernel.o': No such file or directory
> Compiling correlation kernels by nvcc...
> rm: cannot remove 'correlation_cuda_kernel.o': No such file or directory
> Compiling channelnorm kernels by nvcc...
> rm: cannot remove 'ChannelNorm_kernel.o': No such file or directory
> Removing intermediate container 3e5fdad78546
>  ---> d179e38ba7d6
> Successfully built d179e38ba7d6
> Successfully tagged inpainting:latest
And dependent functions:

> appuser@cc1582770918:\~/Deep-Flow$ ./install_scripts.sh
> Compiling resample2d kernels by nvcc...
> Compiling correlation kernels by nvcc...
> Compiling channelnorm kernels by nvcc...
> appuser@cc1582770918:~/Deep-Flow$ exit

I still have such error when running test script. I googled it, might be pytorch version is not compatible with cuda version? 

> /usr/local/lib/python3.5/dist-packages/torch/cuda/__init__.py:114: UserWarning:
>     Found GPU0 Quadro RTX 8000 which requires CUDA_VERSION >= 9000 for
>      optimal performance and fast startup time, but your PyTorch was compiled
>      with CUDA_VERSION 8000. Please install the correct PyTorch binary
>      using instructions from http://pytorch.org
> 
>   warnings.warn(incorrect_binary_warn % (d, name, 9000, CUDA_VERSION))
> [                                                  ] 0/158, elapsed: 0s, ETA:Traceback (most recent call last):
>   File "/home/appuser/Deep-Flow/tools/video_inpaint.py", line 185, in <module>
>     main()
>   File "/home/appuser/Deep-Flow/tools/video_inpaint.py", line 166, in main
>     extract_flow(args)
>   File "/home/appuser/Deep-Flow/tools/video_inpaint.py", line 85, in extract_flow
>     output_file = infer(args)
>   File "/home/appuser/Deep-Flow/tools/infer_flownet2.py", line 53, in infer
>     flow = Flownet(f1, f2)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/appuser/Deep-Flow/models/FlowNet2_Models/FlowNet2.py", line 131, in forward
>     flownetc_flow2 = self.flownetc(x)[0]
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/home/appuser/Deep-Flow/models/FlowNet2_Models/FlowNetC.py", line 75, in forward
>     out_conv1a = self.conv1(x1)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/container.py", line 91, in forward
>     input = module(input)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 491, in __call__
>     result = self.forward(*input, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/conv.py", line 301, in forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

**Comment by houhaol** [comment]
Thanks for your help. I figured it out. I changed the based cuda image and pytorch line. Here is the modified part
`FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04` 

```
RUN pip3 install --no-cache-dir \
    https://download.pytorch.org/whl/cu90/torch-0.4.0-cp35-cp35m-linux_x86_64.whl \
    torchvision==0.2.1
```
